import sqlalchemy
from sqlalchemy import Table, Column, ForeignKey, ...
    Boolean, Date, Float, Integer, String

Base = sqlalchemy.declarative_base()

class Conference(Base):
    __tablename__ = 'conferences'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    subdivision = Column(String)

class Drive(Base):
    __tablename__ = 'drives'
    id = Column(Integer, primary_key=True)
    number = Column(Integer)
    team = Column(Integer, ForeignKey('teams.id'))
    start_period = Column(Integer)
    start_clock = Column(Integer)
    start_spot = Column(Integer)
    start_reason = Column(String)
    end_period = Column(Integer)
    end_clock = Column(Integer)
    end_spot = Column(Integer)
    end_reason = Column(String)
    plays = Column(Integer)
    yards = Column(Integer)
    time_of_poss = Column(Integer)
    red_zon_attempt = Column(Integer)

class Game(Base):
    __tablename__ = 'games'
    id = Column(Integer, primary_key=True)
    date = Column(Date)
    home = Column(Integer, ForeignKey('teams.id'))
    away = Column(Integer, ForeignKey('teams.id'))
    stadium = Column(Integer, ForeignKey('stadiums.id'))
    site = Column(String)
    attendance = Column(Integer)
    duration = Column(Integer)

class Kickoff(Base):
    id = Column(Integer, primary_key=True)
    game = Column(Integer, ForeignKey('games.id'))
    play_number = Column(Integer)
    team = Column(Integer, ForeignKey('teams.id'))
    player = Column(Integer, ForeignKey('players.id'))
    attempt = Column(Integer)
    yards = Column(Integer)
    fair_catch = Column(Boolean)
    touchback = Column(Boolean)
    downed = Column(Boolean)
    out_of_bounds = Column(Boolean)
    onside = Column(Boolean)
    onside_success = Column(Boolean)

class Pass(Base):
    id = Column(Integer, primary_key=True)
    game = Column(Integer, ForeignKey('games.id'))
    play_number = Column(Integer)
    team = Column(Integer, ForeignKey('teams.id'))
    passer_player = Column(Integer, ForeignKey('players.id'))
    receiver_player = Column(Integer, ForeignKey('players.id'))
    attempt = Column(Integer)
    completion = Column(Boolean)
    yards = Column(Integer)
    touchdown = Column(Boolean)
    interception = Column(Boolean)
    first_down = Column(Boolean)
    dropped = Column(Boolean)

class Play(Base):
    __tablename__ = 'plays'
    id = Column(Integer, primary_key=True)
    number = Column(Integer)
    period = Column(Integer)
    clock = Column(Integer)
    offense = Column(Integer, ForeignKey('teams.id'))
    defense = Column(Integer, ForeignKey('teams.is'))
    offense_points = Column(Integer)
    defense_points = Column(Integer)
    down = Column(Integer)
    distance = Column(Integer)
    spot = Column(Integer)
    play_type = Column(String)
    drive_number = Column(Integer)
    drive_play = Column(Integer)

class Player(Base):
    __tablename__ = 'players'
    id = Column(Integer, primary_key=True)
    team = Column(Integer, ForeignKey('teams.id'))
    last_name = Column(String)
    first_name = Column(String)
    number = Column(Integer)
    year = Column(String)
    position = Column(String)
    height = Column(Float)
    weight = Column(Float)
    hometown = Column(String)
    home_state = Column(String)
    home_country = Column(String)
    last_school = Column(String)

class Punt(Base):
    id = Column(Integer, primary_key=True)
    game = Column(Integer, ForeignKey('games.id'))
    play_number = Column(Integer)
    team = Column(Integer, ForeignKey('teams.id'))
    player = Column(Integer, ForeignKey('players.id'))
    attempt = Column(Integer)
    yards = Column(Integer)
    blocked = Column(Boolean)
    fair_catch = Column(Boolean)
    touchback = Column(Boolean)
    downed = Column(Boolean)
    out_of_bounds = Column(Boolean)    

class Return(Base):
    id = Column(Integer, primary_key=True)
    game = Column(Integer, ForeignKey('games.id'))
    play_number = Column(Integer)
    team = Column(Integer, ForeignKey('teams.id'))
    player = Column(Integer, ForeignKey('players.id'))
    attempt = Column(Integer)
    yards = Column(Integer)
    touchdown = Column(Boolean)
    fumble = Column(Boolean)
    fumble_lost = Column(Boolean)
    safety = Column(Boolean)
    fair_catch = Column(Boolean)

class Reception(Base):
    id = Column(Integer, primary_key=True)
    game = Column(Integer, ForeignKey('games.id'))
    play_number = Column(Integer)
    team = Column(Integer, ForeignKey('teams.id'))
    player = Column(Integer, ForeignKey('players.id'))
    reception = Column(Boolean)
    yards = Column(Integer)
    touchdown = Column(Boolean)
    first_down = Column(Boolean)
    fumble = Column(Boolean)
    fumble_lost = Column(Boolean)
    safety = Column(Boolean)

class Rush(Base):
    id = Column(Integer, primary_key=True)
    game = Column(Integer, ForeignKey('games.id'))
    play_number = Column(Integer)
    team = Column(Integer, ForeignKey('teams.id'))
    player = Column(Integer, ForeignKey('players.id'))
    attempt = Column(Integer)
    yards = Column(Integer)
    touchdown = Column(Boolean)
    first_down = Column(Boolean)
    sack = Column(Boolean)
    fumble = Column(Boolean)
    fumble_lost = Column(Boolean)
    safety = Column(Boolean)
    

class Stadium(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    city = Column(String)
    state = Column(String)
    capacity = Column(Integer)
    surface = Column(String)
    year_opened = Column(Integer)

    def __repr__(self):
        return "<Stadium(name=’%s’, location='%s, %s'>" % (
            self.name, self.city, self.state)

class Team(Base):
    __tablename__ = 'teams'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    conference = Column(Integer, ForeignKey('conferences.id'))

class TeamGameStatistics(Base):
    __tablename__ = 'team_game_statistics'
    team = Column(Integer, ForeignKey('teams.id'))
    game = Column(Integer, ForeignKey('games.id'))
    rush_attempts = Column(Integer)
    rush_yards = Column(Integer)
    rush_tds = Column(Integer)
    pass_attempts = Column(Integer)
    pass_completions = Column(Integer)
    pass_yards = Column(Integer)
    pass_tds = Column(Integer)
    pass_interceptions = Column(Integer)
    pass_conversions = Column(Integer)
    kickoff_returns = Column(Integer)
    kickoff_return_yards = Column(Integer)
    kickoff_return_tds = Column(Integer)
    punt_returns = Column(Integer)
    punt_return_yards = Column(Integer)
    punt_return_tds = Column(Integer)
    fumble_returns = Column(Integer)
    fumble_return_yards = Column(Integer)
    fumble_return_tds = Column(Integer)
    interception_returns = Column(Integer)
    interception_return_yards = Column(Integer)
    interception_return_tds = Column(Integer)
    misc_returns = Column(Integer)
    misc_return_yards = Column(Integer)
    misc_return_tds = Column(Integer)
    field_goal_attempts = Column(Integer)
    field_goals_made = Column(Integer)
    offense_xp_attempts = Column(Integer)
    offense_xp_made = Column(Integer)
    offense_2xp_attempts = Column(Integer)
    offense_2xp_made = Column(Integer)
    defense_2xp_attempts = Column(Integer)
    defense_2xp_made = Column(Integer)
    safeties = Column(Integer)
    points = Column(Integer)
    punts = Column(Integer)
    punt_yards = Column(Integer)
    kickoffs = Column(Integer)
    kickoff_yards = Column(Integer)
    kickoff_touchbacks = Column(Integer)
    kickoff_ob = Column(Integer)
    kickoff_onsides = Column(Integer)
    fumble = Column(Integer)
    fumble_lost = Column(Integer)
    tackle_solo = Column(Integer)
    tackle_assisted = Column(Integer)
    tackle_for_loss = Column(Integer)
    sack = Column(Integer)
    sack_yard = Column(Integer)
    qb_hurry = Column(Integer)
    fumbles_forced = Column(Integer)
    passes_broken = Column(Integer)
    kicks_blocked = Column(Integer)
    first_down_rush = Column(Integer)
    first_down_pass = Column(Integer)
    first_down_penalty = Column(Integer)
    time_of_poss = Column(Integer)
    penalty = Column(Integer)
    penalty_yards = Column(Integer)
    third_down_attempts = Column(Integer)
    third_down_conversions = Column(Integer)
    fourth_down_attempts = Column(Integer)
    fourth_down_conversions = Column(Integer)
    red_zone_attempts = Column(Integer)
    red_zone_tds = Column(Integer)
    red_zone_field_goals = Column(Integer)

class PlayerGameStatistics(Base):
    __tablename__ = 'team_game_statistics'
    player = Column(Integer, ForeignKey('teams.id'))
    game = Column(Integer, ForeignKey('games.id'))
    rush_attempts = Column(Integer)
    rush_yards = Column(Integer)
    rush_tds = Column(Integer)
    pass_attempts = Column(Integer)
    pass_completions = Column(Integer)
    pass_yards = Column(Integer)
    pass_tds = Column(Integer)
    pass_interceptions = Column(Integer)
    pass_conversions = Column(Integer)
    receptions = Column(Integer)
    receiving_yards = Column(Integer)
    receiving_tds = Column(Integer)
    kickoff_returns = Column(Integer)
    kickoff_return_yards = Column(Integer)
    kickoff_return_tds = Column(Integer)
    punt_returns = Column(Integer)
    punt_return_yards = Column(Integer)
    punt_return_tds = Column(Integer)
    fumble_returns = Column(Integer)
    fumble_return_yards = Column(Integer)
    fumble_return_tds = Column(Integer)
    interception_returns = Column(Integer)
    interception_return_yards = Column(Integer)
    interception_return_tds = Column(Integer)
    misc_returns = Column(Integer)
    misc_return_yards = Column(Integer)
    misc_return_tds = Column(Integer)
    field_goal_attempts = Column(Integer)
    field_goals_made = Column(Integer)
    offense_xp_attempts = Column(Integer)
    offense_xp_made = Column(Integer)
    offense_2xp_attempts = Column(Integer)
    offense_2xp_made = Column(Integer)
    defense_2xp_attempts = Column(Integer)
    defense_2xp_made = Column(Integer)
    safeties = Column(Integer)
    points = Column(Integer)
    punts = Column(Integer)
    punt_yards = Column(Integer)
    kickoffs = Column(Integer)
    kickoff_yards = Column(Integer)
    kickoff_touchbacks = Column(Integer)
    kickoff_ob = Column(Integer)
    kickoff_onsides = Column(Integer)
    fumble = Column(Integer)
    fumble_lost = Column(Integer)
    tackle_solo = Column(Integer)
    tackle_assisted = Column(Integer)
    tackle_for_loss = Column(Integer)
    sack = Column(Integer)
    sack_yard = Column(Integer)
    qb_hurry = Column(Integer)
    fumbles_forced = Column(Integer)
    passes_broken = Column(Integer)
    kicks_blocked = Column(Integer)

    
